//%attributes = {}
If (False:C215)
	//Project Method Name:      LN_WS_RequestNewLicence
	//------------------ Method Notes ------------------
	
	//------------------ Revision Control ----------------
	//Date Created: 22/06/2009 10:45
	//Created BY: Nigel Greenlee
	//Date Modified: 
	//Modified By DefaultUser
	//Modification notes 
	
End if 
//Variable Declarations
If (True:C214)
	C_BLOB:C604($0)
	C_BOOLEAN:C305(<>Err_bo_ManualHandler; <>ERR_bo_NoErrDialog)
	C_LONGINT:C283(<>Err_l_NoError; $ErrorNumber; IsLicenceHostAlive; LR_l_LicencePortNumber)
	C_TEXT:C284($_t_oldMethodName; $1; $2; $3; $4; $5; $6; LR_t_LicenceHost)
End if 

//Code Starts Here

$_t_oldMethodName:=ERR_MethodTracker("LN_WS_RequestNewLicence")

//
// LN_WS_RequestNewLicence
// http://10.11.0.46:8085/4DWSDL
//
// Method source code automatically generated by the 4D SOAP wizard.
// ----------------------------------------------------------------

//
//
//
//
//
//

LR_Custom
//
WEB SERVICE SET PARAMETER:C777("FourD_arg1"; $1)
WEB SERVICE SET PARAMETER:C777("FourD_arg2"; $2)
WEB SERVICE SET PARAMETER:C777("FourD_arg3"; $3)
WEB SERVICE SET PARAMETER:C777("FourD_arg4"; $4)
WEB SERVICE SET PARAMETER:C777("FourD_arg5"; $5)
WEB SERVICE SET PARAMETER:C777("FourD_arg6"; $6)

//◊NoError:=9913
<>ERR_bo_NoErrDialog:=True:C214
<>Err_bo_ManualHandler:=False:C215

//******************* added 04/04/08 -kmw *****************
//Added  per Nigels request for ping functionality...(call web service was taking up to 30 seconds to run if he was disconnected from the internet so try a ping first with 5 second timeout)
IsLicenceHostAlive:=0
//$ErrorNumber:=NET_Ping (LR_t_LicenceHost;"sometext";IsLicenceHostAlive;5)
IsLicenceHostAlive:=1
If (IsLicenceHostAlive=1)
	WEB SERVICE CALL:C778(LR_t_LicenceHost+":"+String:C10(LR_l_LicencePortNumber)+"/4DSOAP/"; "A_WebService#LN_WS_RequestNewLicence"; "LN_WS_RequestNewLicence"; "http://www.4d.com/namespace/default"; Web Service dynamic:K48:1)
	<>Err_l_NoError:=0
	If (<>Err_bo_ManualHandler)  //we got an error
		
		<>Err_bo_ManualHandler:=False:C215
		SET BLOB SIZE:C606($0; 0)
	Else 
		<>Err_bo_ManualHandler:=False:C215
		If (OK=1)
			WEB SERVICE GET RESULT:C779($0; "FourD_arg0"; *)  // Memory clean-up on the final return value.
		Else 
			
			SET BLOB SIZE:C606($0; 0)
		End if 
	End if 
Else 
	If (<>Err_bo_ManualHandler)
		<>Err_bo_ManualHandler:=False:C215
	End if 
	SET BLOB SIZE:C606($0; 0)
End if 
//*************************************************************
ERR_MethodTrackerReturn("LN_WS_RequestNewLicence"; $_t_oldMethodName)